"""Change description to string

Revision ID: 2e6dbf5f5545
Revises: 97f343e4291e
Create Date: 2025-10-19 19:45:48.264676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6dbf5f5545'
down_revision: Union[str, Sequence[str], None] = '97f343e4291e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1024),
               existing_nullable=False,
               schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.String(length=1024),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='db_schema')
    # ### end Alembic commands ###
