"""int_bigint_user_id

Revision ID: 97f343e4291e
Revises: 728f6c3f9014
Create Date: 2025-10-17 16:22:13.255231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f343e4291e'
down_revision: Union[str, Sequence[str], None] = '728f6c3f9014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'id_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('baskets', 'id_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('favorites', 'id_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('orders', 'id_user',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('favorites', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('baskets', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='db_schema')
    op.alter_column('addresses', 'id_user',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='db_schema')
    # ### end Alembic commands ###
