"""orders_status

Revision ID: b7a72af2bd27
Revises: 2e6dbf5f5545
Create Date: 2025-10-23 22:38:06.852296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a72af2bd27'
down_revision: Union[str, Sequence[str], None] = '2e6dbf5f5545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=False), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status', schema='db_schema')
    # ### end Alembic commands ###
